import {Metadata} from "next";
import "./global.css";
import HeaderComponent from "@/components/header/Header";
import {Inter, Archivo} from "next/font/google";
import FooterComponent from "@/components/footer/Footer";

export const metadata: Metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
})

const archivo = Archivo({
    subsets: ["latin"],
    variable: "--font-archivo",
})

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${inter.variable} ${archivo.variable} font-sans flex flex-col h-screen`}>
                <header>
                    <HeaderComponent/>
                </header>
                <main className={"flex-1"}>
                    {children}
                </main>
                <footer className={""}>
                    <FooterComponent />
                </footer>
            </body>
        </html>
    )
}
